name: CI/CD - Build, Push e Deploy AWS

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ”¹ Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: ðŸ”¹ Login no Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: ðŸ”¹ Build das imagens
        run: |
          docker build -t yasmimkethelen/backend:latest -f backend/Dockerfile .
          docker build -t yasmimkethelen/frontend:latest -f frontend/Dockerfile .

      - name: ðŸ”¹ Push das imagens pro Docker Hub
        run: |
          docker push yasmimkethelen/backend:latest
          docker push yasmimkethelen/frontend:latest

      - name: ðŸ”¹ Conectar na instÃ¢ncia EC2 e atualizar Kubernetes
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/angular-ecommerce-app/k8s
            kubectl apply -k .
            kubectl rollout restart deployment backend -n app-demo
            kubectl rollout restart deployment frontend -n app-demo
            kubectl get pods -n app-demo
